#define AIR720SDHG_USB_DEVICE_VENDOR_ID  0x1286
#define AIR72XUX_USB_DEVICE_VENDOR_ID  0x1782
#define AIR72XCX_USB_DEVICE_VENDOR_ID  0x2ecc
#define AIR780E_USB_DEVICE_VENDOR_ID  0x19d1

#define AIRM2M_USB_DEVICE_DIAG_INTERFACE_ID 4//4
#define AIRM2M_USB_DEVICE_AT_INTERFACE_ID 2//2
#define AIRM2M_USB_DEVICE_PPP_INTERFACE_ID 6//6

char* FindUsbDevice(int device_interface_id);

